import AvatarUI from './AvatarUI';
import ButtonUI from './ButtonUI';
import CardUI from './CardUI';
import InputUI from './InputUI';
import IconCircleUI from './IconCircleUI';
import IconUI from './IconUI';
import LinkButtonUI from './LinkButtonUI';
import ModalUI from './ModalUI';
import { RadioUI, RadioGroupUI } from './RadioUI';
import { PersistBtnPainelUI, PersistPainelUI, PersistLineUI } from './PersistUI';
import SelectBoxUI from './SelectBoxUI';
import SelectUI from './SelectUI';
import TagUI from './TagUI';
import TypographyUI from './TypographyUI';
import DatePickerUI from './DatePickerUI';
import TableUI from './TableUI';
import InputButtonUI from './InputButtonUI';
import PopoverUI from './PopoverUI';
import ToolSearchTableUI from './ToolSearchTableUI';
import ContainerPersistUI from './ContainerPersistUI';
import CheckBoxUI from './CheckBoxUI';

export const Avatar = AvatarUI;
export const CheckBox = CheckBoxUI;
export const PersistBtnPainel = PersistBtnPainelUI;
export const PersistLine = PersistLineUI;
export const PersistPainel = PersistPainelUI;
export const ContainerPersist = ContainerPersistUI;
export const InputButton = InputButtonUI;
export const ToolSearchTable = ToolSearchTableUI;
export const Popover = PopoverUI;
export const Button = ButtonUI;
export const Card = CardUI;
export const Input = InputUI;
export const IconCircle = IconCircleUI;
export const Icon = IconUI;
export const LinkButton = LinkButtonUI;
export const Modal = ModalUI;
export const Radio = RadioUI;
export const RadioGroup = RadioGroupUI;
export const SelectBox = SelectBoxUI;
export const Select = SelectUI;
export const Tag = TagUI;
export const Typography = TypographyUI;
export const DatePicker = DatePickerUI;
export const Table = TableUI;
